title = "UOC Site Template"
baseURL = "/"
DefaultContentLanguage = "ca"
defaultContentLanguageInSubdir = true
theme = "web-uoc-1"

[languages]

  [languages.ca]
    title = "Blog UOC - ca"
    weight = 1
    languageName = "Català"
