backend:
  branch: master
  name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "section"
    label: "Create new section"
    folder: "content"
    create: true
    slug: "{{folder}}/_index.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Folder", name: "folder", widget: "string", required: true, default: "/"}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false 