backend:
  branch: master
  name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "Create section"
        name: "create"
        file: "tasks/tasks.json"
        fields:
          - {label: "Folder", name: "absfolder", widget: string, required: true}
