backend:
  branch: master
  name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "content"
    label: "Contingut"
    folder: "content/section1/subsection1"
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Autor", name: "author", widget: "string", required: true}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false

  - name: "section_ca"
    label: "Crea una nova secció"
    folder: "content/section1/subsection1"
    create: true
    filter: {field: "language", value: "ca"}    
    slug: "/{{folder}}/{{slug}}.ca"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Folder", name: "folder", widget: "string", required: false}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false

  - name: "section_es"
    label: "Crea una nueva sección"
    folder: "content/section1/subsection1"
    create: true
    filter: {field: "language", value: "es"}    
    slug: "/{{folder}}/{{slug}}.es"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Folder", name: "folder", widget: "string", required: false}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

  - name: "section_en"
    label: "Create new section"
    folder: "content/section1/subsection1"
    create: true
    filter: {field: "language", value: "en"}    
    slug: "/{{folder}}/{{slug}}.en"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Folder", name: "folder", widget: "string", required: false}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false                  