backend:
  branch: master
  name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - label: "Setup"
    name: "config"
    files:
      - label: "Create section"
        name: "create"
        file: "tasks/tasks.json"
        fields:
          - {label: "Route", name: "route", widget: "hidden", default: "./content/"}
          - {label: "Folder", name: "folder", widget: "string", required: true}

