backend:
  branch: master
  name: github
  repo: davidayalas/static-site-uoc   # Path to your Github repository
  base_url: https://netlify-oauth.azurewebsites.net/ # Path to ext auth provider

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "content"
    label: "Content"
    folder: "content/section1"
    filter: {field: "contenttype", value: "content"}    
    create: true
    slug: "{{urlkey}}.{{language}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Content Type", name: "contenttype", widget: "hidden", default: "content"}
      - {label: "Language", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Key (for translations linking)", name: "urlkey", widget: "string", required: true}
      - {label: "Sort", name: "weight", widget: "number", default: 1}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false