backend:
  name: github
  repo: davidayalas/ssg-huguoc 
  branch: master
  #base_url: http://netlify-oauth.azurewebsites.net # Path to ext auth provider


media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "aq"
    label: "Arquitectura"
    folder: "content/aq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Ordre", name: "weight", widget: "number", required: false}
      - name: Blocs
        label: Bloc informacio
        widget: list
        required: false
        fields:
          - {label: "Títol", name: "titol", widget: string}
          - {label: "Contingut", name: "contingut", widget: markdown}      
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}

  - name: "bi"
    label: "Business Intelligence"
    folder: "content/bi"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Ordre", name: "weight", widget: "number", required: false}
      - name: Blocs
        label: Bloc informacio
        widget: list
        fields:
          - {label: "Títol", name: "titol", widget: string}
          - {label: "Contingut", name: "contingut", widget: markdown}      
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
